### ISSUE TITLE
2乗したままなのでsqrt()の追加

### ISSUE THREAD

**Issue by testusuke** [AzisabaNetwork/RealChat#1]

**Comment by huda0209** [comment]
https://github.com/AzisabaNetwork/RealChat/commit/bbd2a91376949c2aec4cd205f621c8a9cd39f5d9
https://github.com/AzisabaNetwork/RealChat/blob/bbd2a91376949c2aec4cd205f621c8a9cd39f5d9/src/main/java/com/github/huda0209/realchat/util/playerDistance.java#L14
修正
